# Welcome to the Hugo configuration file.
# Hugo is used for building the status page,
# so this file can be used to change how
# your status page should behave or look.

# What is your status page called?
# Shows up in the browser bar and meta tags
title: Example Inc. Status

# What language is this page in?
# Only alters the html[lang] attribute
languageCode: en-US

# What is the hostname or path to the root?
# Where is the site hosted?
# Example: https://status.example.com/
baseURL: https://status.example.com/

# Should posts, which have a publish date
# from the future, be built? Useful for
# sharing upcoming maintenance, etc.
#
# We recommend to keep this at `true`.
# BOOLEAN; `true`, `false`
buildFuture: true

params:
  # These are your systems. Change them to
  # change the amount of components.
  systems:
    - Core
    - EU
    - US

  # Should we show the logo or the title
  # of the status page?
  useLogo: false

  # Where is the logo located, if one is
  # present at all?
  logo: /logo.png

  # This is the description that is shown
  # in the footer and meta tags.
  description: We continuously monitor the status of our services and if there are any interruptions, a note will be posted here.

  # Cplors throughout cState
  #
  # Defaults:
  #
  # ok: 228B22
  # warning: DC143C
  # down: FF8C00
  # notice: 708090
  # border: dfdfdf
  # faded: ccc
  ok: 228B22
  disrupted: FF8C00
  down: DC143C
  notice: 708090
  border: dfdfdf
  faded: ccc

# These options affect the core of cState.
# Please do not change them if you do not
# know what you are doing.
theme: cstate
