name = "cstate"
license = "MIT"
licenselink = "https://github.com/mistermantas/cstate/blob/master/LICENSE.md"
description = "Ãœber fast, backwards compatible (IE8+), tiny, and simple status page built with Hugo. Compatible with Netlify & GitHub Pages."
homepage = "https://github.com/mistermantas/cstate"
tags = ['hugo', 'netlify', 'status', 'statuspage', 'fast', 'light', 'ie8', 'ie9', 'ie10', 'ie11', 'github', 'github-pages', 'gh-pages', 'serverside', 'serverless', 'no-javascript', 'github-page', 'netlify-cms', 'gh-pages', 'responsive', 'minimal', 'google analytics', 'clean', 'minimalist', 'light', 'product', 'technical', 'widgets', 'products', 'mobile', 'onepage', 'singlepage', 'single page', 'spa']
min_version = "0.28"

[author]
  name = "mistermantas"
  homepage = "https://github.com/mistermantas"
